import 'dotenv/config';

const {
  DEV_DB_USER,
  DEV_DB_HOST,
  DEV_DB_NAME,
  DEV_DB_PASSWORD,
  DEV_DB_PORT,
  DEV_PORT,
  DEV_SECRET,
  DEV_NODE_ENV,
  DEV_RABBIT_MQ_URL,
  DEV_DATABASE_URL
} = process.env;

export default {
  DATABASE_USER: DEV_DB_USER,
  DATABASE_PASSWORD: DEV_DB_PASSWORD,
  DATABASE_HOST: DEV_DB_HOST,
  DATABASE_NAME: DEV_DB_NAME,
  DATABASE_PORT: DEV_DB_PORT,
  AUTHENTICATION_SECRET: DEV_SECRET,
  PORT: DEV_PORT,
  NODE_ENV: DEV_NODE_ENV,
  RABBIT_MQ_URL: DEV_RABBIT_MQ_URL,
  DATABASE_URL: DEV_DATABASE_URL
};
