import 'dotenv/config';

const {
  TEST_DB_USER,
  TEST_DB_HOST,
  TEST_DB_NAME,
  TEST_DB_PASSWORD,
  TEST_DB_PORT,
  TEST_PORT,
  TEST_SECRET,
  TEST_NODE_ENV,
  TEST_RABBIT_MQ_URL,
  TEST_DATABASE_URL
} = process.env;

export default {
  DATABASE_USER: TEST_DB_USER,
  DATABASE_PASSWORD: TEST_DB_PASSWORD,
  DATABASE_HOST: TEST_DB_HOST,
  DATABASE_NAME: TEST_DB_NAME,
  DATABASE_PORT: TEST_DB_PORT,
  AUTHENTICATION_SECRET: TEST_SECRET,
  PORT: TEST_PORT,
  NODE_ENV: TEST_NODE_ENV,
  RABBIT_MQ_URL: TEST_RABBIT_MQ_URL,
  DATABASE_URL: TEST_DATABASE_URL
};